export const QUOTATION_CREATE_REQUEST = 'QUOTATION_CREATE_REQUEST';
export const QUOTATION_CREATE_SUCCESS = 'QUOTATION_CREATE_SUCCESS';
export const QUOTATION_CREATE_FAIL = 'QUOTATION_CREATE_FAIL';
export const QUOTATION_CREATE_RESET = 'QUOTATION_CREATE_RESET';

export const QUOTATION_DETAILS_REQUEST = 'QUOTATION_DETAILS_REQUEST';
export const QUOTATION_DETAILS_SUCCESS = 'QUOTATION_DETAILS_SUCCESS';
export const QUOTATION_DETAILS_FAIL = 'QUOTATION_DETAILS_FAIL';

export const QUOTATION_LIST_REQUEST = 'QUOTATION_LIST_REQUEST';
export const QUOTATION_LIST_SUCCESS = 'QUOTATION_LIST_SUCCESS';
export const QUOTATION_LIST_FAIL = 'QUOTATION_LIST_FAIL';

export const QUOTATION_DELETE_REQUEST = 'QUOTATION_DELETE_REQUEST';
export const QUOTATION_DELETE_SUCCESS = 'QUOTATION_DELETE_SUCCESS';
export const QUOTATION_DELETE_FAIL = 'QUOTATION_DELETE_FAIL';
export const QUOTATION_DELETE_RESET = 'QUOTATION_DELETE_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';